import record from "N/record";

import { paramCommand } from "../../constants.js";
import { interpolate, documentationSection } from "../../html.js";
import { scriptDeployParam } from "../../url.js";
import { splitVerticalBar, listsEqual } from "../../utils.js";
import { parseFieldAssignmentList } from "../../field-assignments.js";
import { getRecordType } from "../../record-types.js";
import editRecordsPage, { setRecordField } from "../edit-records/server.js";
import lookupFieldsPage from "../lookup-fields/server.js";
import templateHtml from "./template.html";


const commandName = "create";


export default {
	name: "create-records",
	label: "Create Records",

	render(context) {
		return interpolate(templateHtml, {
			commandUrl: scriptDeployParam(context) + "&" + paramCommand + "=" + commandName,
			documentationHtml: documentationSection(`
				<h3>· For Record Type, see [${lookupFieldsPage.label}] page (left menu)</h3>
				<h3>· Default Values and Field Values have the following format:</h3>
				<h4>&nbsp; &nbsp; · &lt;Field ID&gt;=&lt;Field Value&gt;</h4>
				<h4>&nbsp; &nbsp; · Can specify multiple field values, separated by &amp;</h4>
				<h3>· To determine which values are "Default Values" (vs Field Values):</h3>
				<h4>&nbsp; &nbsp; · Refer to SuiteScript documentation (incomplete):
					<a href="https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_4267255811.html#bridgehead_4423371543">
						"N/record Default Values"
					</a>
				</h4>
				<h4>&nbsp; &nbsp; · For some Records Types, certain Default Values are mandatory</h4>
				<h3>· Result contains the new Internal ID that is automatically generated by NetSuite</h3>
				<h3>· Sublists are not supported during creation (use [${editRecordsPage.label}] after)</h3>
			`),
		});
	},

	commands: {
		[commandName]: handleCreateRecord,
	},
};


function handleCreateRecord(context) {
	let recordId;
	try {
		const tabDelimitedRows = JSON.parse(context.request.body);
		const firstTabDelimitedRow = tabDelimitedRows[0];
		const firstParts = splitVerticalBar(firstTabDelimitedRow);
		const recordType = getRecordType(firstParts[0]);
		const defaultFieldValues = parseFieldAssignmentList(firstParts[1] || "");
		const fieldValues = parseFieldAssignmentList(firstParts[2] || "");

		const allValidators = [];

		const defaultValues = {};

		const rec = record.create({
			type: recordType,
			defaultValues,
		});

		for (const fieldValue of defaultFieldValues) {
			const validator = setDefaultRecordField(rec, fieldValue.fieldId, fieldValue.fieldText);
			allValidators.push(validator);
		}

		recordId = rec.save({});

		const loaded = record.load({
			type: recordType,
			id: recordId,
		});

		for (const fieldValue of fieldValues) {
			const validator = setRecordField(loaded, fieldValue.fieldId, fieldValue.fieldText);
			allValidators.push(validator);
		}

		loaded.save({});

		const reload = record.load({
			type: recordType,
			id: recordId,
		});

		const messages = [];
		for (const validator of allValidators) {
			try {
				messages.push(validator(reload));
			}
			catch (e) {
				messages.push(`Unable to validate: ${e.message}`);
			}
		}

		return JSON.stringify([
			`Internal ID: ${recordId} | ${messages.join(" | ")}`,
		]);
	}
	catch (e) {
		const prefix = recordId == null
			? "Error: "
			: `Error after creating Internal ID ${recordId}: `;
		return JSON.stringify([prefix + e.message]);
	}
}


function setDefaultRecordField(rec, fieldId, fieldText) {
	const field = rec.getField({fieldId});
	if (field.type === "select" || field.type === "multiselect") {
		return setDefaultRecordSelect(rec, fieldId, fieldText, field.type === "multiselect");
	}

	if (Array.isArray(fieldText)) {
		throw new Error(
			"Single value expected (" + fieldId + "): " + fieldText);
	}

	rec.setText({
		fieldId,
		text: fieldText,
	});

	return reload => {
		const afterSave = reload.getText({fieldId});
		return afterSave === fieldText
			? `Default ${fieldId} to '${fieldText}'`
			: `Unexpected ${fieldId} default, tried '${fieldText}' but got '${afterSave}'`;
	};
}


function setDefaultRecordSelect(rec, fieldId, fieldText, multi) {
	const asList = Array.isArray(fieldText) ? fieldText : [fieldText];
	if (! multi && asList.length > 1) {
		throw new Error(
			"Single value expected (" + fieldId + "): " + fieldText);
	}

	const allIds = asList.every(i => /^-?\d+$/.test(i.trim()));
	const someIds = asList.some(i => /^-?\d+$/.test(i.trim()));
	if (someIds && ! allIds) {
		throw new Error(
			"All must be text or all must be IDs (" + fieldId + "): " + fieldText);
	}

	if (allIds) {
		const fieldValues = asList.map(i => parseInt(i));
		rec.setValue({
			fieldId,
			value: (multi ? fieldValues : fieldValues[0]),
		});
		return reload => {
			const afterSave = reload.getValue({fieldId});
			const afterSaveList = Array.isArray(afterSave) ? afterSave : [afterSave];
			return listsEqual(asList, afterSaveList)
				? `Default ${fieldId} to '${fieldText}'`
				: `Unexpected ${fieldId} default, tried '${fieldText}' but got '${afterSave}'`;
		};
	}

	rec.setText({
		fieldId,
		text: (multi ? asList : asList[0]),
	});

	return reload => {
		const afterSave = reload.getText({fieldId});
		const afterSaveList = Array.isArray(afterSave) ? afterSave : [afterSave];
		return listsEqual(asList, afterSaveList)
			? `Default ${fieldId} to '${fieldText}'`
			: `Unexpected ${fieldId} default, tried '${fieldText}' but got '${afterSave}'`;
	};
}
